version: '3'
services:
  backend:
    build:
      context: ./postit_backend
    ports:
      - 3000:3000

  frontend:
    depends_on:
      - "backend"
    build:
      context: ./postit_frontend
    ports:
      - 80:8080